apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wlw0vbji9-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wlw0vbji9-java-quarkus-gitops